### ISSUE TITLE
PropTypes and general React 16 compatibility

### ISSUE THREAD

**Issue by albertkim** [rma-consulting/react-easy-chart#103]
The library still uses React.PropTypes, which will be deprecated as of React 16.

Proposed solution:
Update the library to use the `prop-types` library, as well as update any third party dependencies that may be React 16 incompatible.

**Comment by iamcaleberic** [comment]
This is true...Tried it with React 16 and everything breaks.

**Comment by albertkim** [comment]
I don't think this library is maintained anymore, so for anyone reading this post, I've been looking into some similar alternatives. I've been trying out `react-vis`, and it's been getting the job done for me - simple configuration, pretty defaults, and easy to use.

https://github.com/uber/react-vis

**Comment by sat-** [comment]
Hi @albertkim and @iamcaleberic, I've migrated the code to use the prop-types library now.
