### ISSUE TITLE
d3-array module not found error when using

### ISSUE THREAD

**Issue by email2vimalraj** [rma-consulting/react-easy-chart#104]
Hello,

I'm getting the following error when I use `PieChart`:

```
./~/react-easy-chart/lib/shared.js
Module not found: Can't resolve 'd3-array' in '../node_modules/react-easy-chart/lib'
```

**Comment by email2vimalraj** [comment]
I guess this is because of your peer dependencies.

**Comment by ngocdaothanh** [comment]
I think you need to manually install "peerDependencies" listed at:
https://github.com/rma-consulting/react-easy-chart/blob/master/package.json#L95

**Comment by email2vimalraj** [comment]
Thanks
