### ISSUE TITLE
package dependencies are broken 

### ISSUE THREAD

**Issue by radjivC** [rma-consulting/react-easy-chart#110]
![screen shot 2017-11-02 at 6 44 27 pm](https://user-images.githubusercontent.com/5714138/32314864-e16e8178-bffd-11e7-892a-64b98dd6df15.png)

**Comment by admiral-fairbanks-ExtolInc** [comment]
I had the same issue just today. I'm downgrading to d3@^3.5.17 for now in the hopes that this fixes it.
![image](https://user-images.githubusercontent.com/30904116/32552858-40214714-c463-11e7-81bc-7fb0ecbd32f0.png)

**Comment by njwest** [comment]
I was able to get react-easy-charts to run with `yarn add d3-scale` and `react-faux-dom`, as these appear to be the two dependencies missing from the latest release

**Comment by jundialwan** [comment]
It is.
When installing, npm warn me to install these dependencies by myself:
* d3
* d3-array
* d3-scale
* d3-shape
* d3-time-format
* react-faux-dom

Yet, I don't know if I have to install it all or maybe just some of it to just running simple doughnut chart.

**Comment by mbntex** [comment]
I see the list of missing peer dependencies, with terminal WARNs, but when I try to manually install each the peer dependencies they do not seem to meet the requirements of the module. I have tried an older version of d3, but still no resolution. In the client console, I am getting the category 20 error as well. I will try yarn. I wonder if npm 3 no longer auto-installing peer dependencies is the issue...

**Comment by njwest** [comment]
I have this issue with Yarn now too, my `d3-scale` and `react-faux-dom` fix from last month no longer works.

It seems this package only works with a very specific set of D3, NPM, and React versions...
