### ISSUE TITLE
How to use 2 types of charts together?

### ISSUE THREAD

**Issue by ArthurBugan** [rma-consulting/react-easy-chart#123]
I was thinking about use this lib in my React Project, but I need to use 2 differents types of graphs together is there a way? Its Line and Area

**Comment by barabba9174** [comment]
The easiest way is via css, for example if you want the second series as a line you can use:
.areaChart > .area:nth-child(1) { fill: none !important; }

**Comment by ArthurBugan** [comment]
Thank you, I didnt start to use this library on my project, but it looks good.
