### ISSUE TITLE
IE10 bar chart doesn't render

### ISSUE THREAD

**Issue by thienanle** [rma-consulting/react-easy-chart#81]
Seems most charts render fine in IE10, except the bar chart (http://rma-consulting.github.io/react-easy-chart/docs/bar-chart/index.html).

**Comment by harunhasdal** [comment]
Thanks @thienanle for raising this. This issue has been addressed before in the context of #42 however it seems the docs site wasn't updated. 
I have rebuilt the docs site, would be great if you can check and see if your specific problem is resolved.

**Comment by thienanle** [comment]
@harunhasdal The docs site displays the bar chart just fine, but the line/area charts pages don't show. Here's the error:

> Object doesn't support property or method 'findIndex'
> Object doesn't support property or method 'includes'

Should be easily fixed with es6shim.
