### ISSUE TITLE
Documentation for Legend

### ISSUE THREAD

**Issue by sailhenz** [rma-consulting/react-easy-chart#82]
The documentation for legend is a broken link. Can you help to put it back please? Thank you! :)

**Comment by harunhasdal** [comment]
It seems the legend docs were generated in a different way. Fixing that now, so that the docbuild task output will also include the legend page.

**Comment by harunhasdal** [comment]
This is now fixed.
http://rma-consulting.github.io/react-easy-chart/legend/index.html
