### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by LoriKarikari** [rma-consulting/react-easy-chart#87]
Hi,

One of the features is that the charts are responsive but I can't find out how.
You can set a fixed width and height but percentages don't work.
I also tried to add styling to the BarChart component itself but if only affects the container and the chart stays small.

**Comment by LoriKarikari** [comment]
Oooh nevermind found it! The solution can be found in the docs under fluid. Read through the docs but must have missed that one. My bad.
Amazing package btw!

**Comment by chadsteele** [comment]
I also see the claim and the brief discussion of fluid here
[https://rma-consulting.github.io/react-easy-chart/scatterplot-chart/index.html#fluid](https://rma-consulting.github.io/react-easy-chart/scatterplot-chart/index.html#fluid)
but I can't find any instructions online.  Do you have a link?

**Comment by spsaucier** [comment]
@chadsteele I had the same question - See https://rma-consulting.github.io/react-easy-chart/bar-chart/index.html#fluid for a better example.
