### ISSUE TITLE
Not compatible with d3 v4.

### ISSUE THREAD

**Issue by greygatch** [rma-consulting/react-easy-chart#92]
In v4, it looks like the color scaling methods have changed. I'd guess other methods have changed, too.

For example, `d3.scale.category20()` is no longer a thing. [See v4 docs.](https://github.com/d3/d3-scale/blob/master/README.md#schemeCategory20)

**Comment by designsbytraina** [comment]
Are there plans to support v4? Getting the `Uncaught TypeError: Cannot read property 'category20' of undefined` error at the moment. Planning to downgrade d3 in the meantime.

**Comment by jstray** [comment]
Same problem here.

**Comment by greygatch** [comment]
I've begun to update the code here:

https://github.com/greygatch/react-easy-chart/tree/feature/update-for-d3-v4

**Comment by harunhasdal** [comment]
Great effort @greygatch, please make a PR when you think it is ready

**Comment by greygatch** [comment]
@harunhasdal I'm having some trouble initializing the pie charts.  Could you take a look at the index files from that branch in modules/pie-chart?

**Comment by harunhasdal** [comment]
We moved to d3 v4 in 1.0.0 release
