### ISSUE TITLE
Warning when building react-easy-chart module in webpack

### ISSUE THREAD

**Issue by bherila** [rma-consulting/react-easy-chart#97]
After `npm install react-easy-chart` when I try to build the webpack bundle, I get a warning:

> WARNING in ../~/react-easy-chart/~/object-hash/dist/object_hash.js
> Critical dependencies:
> 1:383-390 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
>  @ ../~/react-easy-chart/~/object-hash/dist/object_hash.js 1:383-390

Any suggested way of fixing that?

**Comment by manodupont** [comment]
Whats the solution ?
